name: Dev - Apply
on: [workflow_dispatch]
jobs:
  TerraformApply:
    runs-on: self-hosted
    env:
      vault_token: ${{ secrets.vault_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault-int.rdevopsb84.online:8200/
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            roboshop-infra/data/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            roboshop-infra/data/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;
            roboshop-infra/data/azure-sp ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID ;
      - name: Terraform Apply
        run: |
           export ARM_CLIENT_ID="${{ env.ARM_CLIENT_ID }}"
           export ARM_CLIENT_SECRET="${{ env.ARM_CLIENT_SECRET }}"
           export ARM_TENANT_ID="${{ env.ARM_TENANT_ID }}"
           export ARM_SUBSCRIPTION_ID="${{ env.ARM_SUBSCRIPTION_ID }}"
           mkdir -p /home/github/.kube
           kubectl config set-cluster dummy-cluster --server=https://1.2.3.4 --insecure-skip-tls-verify=true
           make dev-apply token=${vault_token}


