name: Dev - Apply
on: [workflow_dispatch]
jobs:
  TerraformApply:
    runs-on: self-hosted
    env:
      vault_token: ${{ secrets.vault_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault-int.rdevopsb84.online:8200/
          token: ${{ secrets.vault_token }}
          secrets: |
            secret/data/roboshop-infra/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            secret/data/roboshop-infra/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            secret/data/roboshop-infra/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;
            secret/data/roboshop-infra/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
      - name: Terraform Apply
        run: |
           export ARM_CLIENT_ID="${{ env.ARM_CLIENT_ID }}"
           export ARM_CLIENT_SECRET="${{ env.ARM_CLIENT_SECRET }}"
           export ARM_TENANT_ID="${{ env.ARM_TENANT_ID }}"
           export ARM_CLIENT_ID="${{ env.ARM_CLIENT_ID }}"
           make dev-apply token=${vault_token}

